[project]
name = "macbook-lid-to-wiz"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pybooklid>=1.0.0",
    "pywizlight>=0.6.3",
]
